### ISSUE TITLE
Add vue story indexer to support storyStoryv7

### ISSUE THREAD

**Issue by tobiasdiez** [tobiasdiez/storybook-vue-addon#30]
Similar to https://github.com/storybookjs/addon-svelte-csf/blob/ad8c44f6c7c64c1ab83be63f038456e0a5b6c30f/src/preset/index.js#L53-L61.

To test: remove `storyStoreV7: false,` in vite example

**Comment by JReinhold** [comment]
Let me know if you need any guidance @tobiasdiez. While @j3rem1e built the indexer for `addon-svelte-csf`, I've been looking through it quite a bit to understand how it works and what it needs to do.

**Comment by tobiasdiez** [comment]
Thanks for the offer @JReinhold. Taking the svelte code as an example, this was not too hard to implement. The only thing that is not clear to me is how to generate the story id. The current solution (file name + story name) works locally but chromatic has issues with it, see https://github.com/tobiasdiez/storybook-vue-addon/pull/38.
