### ISSUE TITLE
Ability to add docs

### ISSUE THREAD

**Issue by andreasvirkus** [tobiasdiez/storybook-vue-addon#49]
It'd be great if we could easily add documentation in our SFC stories, akin to the MDX experience. Maybe a `<Docs>` component could help us more easily extract this?

**Comment by tobiasdiez** [comment]
Can you explain a bit more what you want to do? Under the hood, the addon translates vue story files into the classical [Component Story Format](https://storybook.js.org/docs/react/api/csf). But I don't think that CSF provides a way to specify documentation.

**Comment by andreasvirkus** [comment]
Even adding the [description](https://storybook.js.org/docs/react/writing-docs/doc-blocks#description) would be a nice start (available in story params). But with MDX you can document various use-cases as freeform text, sprinkling in the component between text blocks. That'd be ideal for us.

An example use-case would be describing the UX rules behind validation errors, where we'd want to show different cases (e.g. the whole field component in an error state, with the validation error being displayed vs just the input field's border indicating a validation error) and explain when to display each.

**Comment by tobiasdiez** [comment]
And how do you want to declare the documentation part? Do you just want to have a `<docs lang=mdx>...</docs>` block where you can put whatever you would normally put in the mdx file? This is possible (see https://github.com/johnsoncodehk/vite-plugin-vue-component-preview for a similar idea), but requires quite a bit of setup to get right (in particular to get linter + ide support).

**Comment by tobiasdiez** [comment]
Support for a `docs` custom block is now added (see readme for details). Please give it a try 🚀
