### ISSUE TITLE
Error:   Failed to scan for dependencies from entries

### ISSUE THREAD

**Issue by ms2d** [tobiasdiez/storybook-vue-addon#60]
I am unable to get this plugin to work inside a VS Code Dev Container. Here are the steps to build the test case:

First, VS Code requires a few top-level files:

    .devcontainer
    ├── Dockerfile
    └── devcontainer.json

The Dockerfile is pretty basic:

    FROM node:19
    USER root

    RUN npm install -g auto-changelog prettier

as is .devcontainer.json

    {
      "name": "JS Environment",
      "dockerFile": "Dockerfile",
      "runArgs": ["--network=host"],
      "appPort": ["5173:5173", "6006:6006"]
    }

#### 1. Initialize a new `vite/vue3` project
All from within a Dev Container via VS Code:

    npm init -y vite@latest catalog -- --template vue
    cd test

#### 2. Configure HMR
Edit `vite.config.js`

    import { defineConfig } from 'vite'
    import vue from '@vitejs/plugin-vue'

    // https://vitejs.dev/config/
    export default defineConfig({
      plugins: [vue()],
      server: {
        base: '',
        open: true,
        host: true
      }
    })

#### 3. Install Vite/Vue3 and add Storybook and the Storybook Vue Addon

    npm install
    npx storybook@latest init
    npm i -S storybook-vue-addon

#### 4. Configure `.storybook/main.js` as in the docs

    /** @type { import('@storybook/vue3-vite').StorybookConfig } */
    const config = {
      stories: [
        '../src/**/*.mdx', 
        '../src/**/*.stories.@(js|jsx|ts|tsx|vue)'
      ],
      addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        '@storybook/addon-interactions',
        'storybook-vue-addon',
      ],
      framework: {
        name: '@storybook/vue3-vite',
        options: {},
      },
      docs: {
        autodocs: 'tag',
      },
    }
    export default config

#### 5. Create sample story

    touch Button.stories.vue

and in `Button.stories.vue`

    <template>
      <Stories>
        <Story title="Unchecked">
          <Checkbox label="Unchecked" />
        </Story>
      </Stories>
    </template>
    <docs>
      import { Canvas } from '@storybook/blocks';
      <Canvas of={Unchecked} />
    </docs>

#### 6. Test the addon

    npm run storybook

#### Resulting error message

    Error:   Failed to scan for dependencies from entries:
      /workspaces/dev/catalog/src/stories/Button.stories.js
    /workspaces/dev/catalog/src/stories/Button.stories.vue
    /workspaces/dev/catalog/src/stories/Header.stories.js
    /workspaces/dev/catalog/src/stories/Page.stories.js
    
      ✘ [ERROR] Do not know how to load path: html:/workspaces/dev/catalog/src/stories/Button.stories.vue?vue&type=stories

        <stdin>:2:7:
          2 │ import "/workspaces/dev/catalog/src/stories/Button.stories.vue"
            ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        at failureErrorWithLog (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1636:15)
        at /workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1048:25
        at runOnEndCallbacks (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1471:45)
        at buildResponseToResult (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1046:7)
        at /workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1058:9
        at new Promise (<anonymous>)
        at requestCallbacks.on-end (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:1057:54)
        at handleRequest (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:723:19)
        at handleIncomingPacket (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:745:7)
        at Socket.readFromStdout (/workspaces/dev/catalog/node_modules/esbuild/lib/main.js:673:7)

I've been trying to figure this out ALL weekend. Hopefully it's something obvious. Thanks :)

**Comment by ms2d** [comment]
So it turns out TailwindCSS has nothing to do with this error. Removing it and rebuilding with just Vite/Vue/Storybook 7 and the Storybook Vue Addon yields the exact same error...

**Comment by ms2d** [comment]
Okay, so apparently developing inside a Docker container was a complete Red Herring, as I have just managed to reproduce the exact same error message (having installed the following test case, outside of the container).

From anywhere on your computer,

    npm i -g n # allows you to manage multiple versions of npm
    n 16 # switch to node v. 16
    
    mkdir storybook
    npm init -y vite@latest storybook -- --template vue
    cd storybook && npm install

Copy the following template to your `vite.config.js` file:

    import vue from '@vitejs/plugin-vue'
    import { defineConfig } from 'vite'
    
    // https://vitejs.dev/config/
    export default defineConfig({
      plugins: [vue()],
      server: {
        base: './',
        open: true, // open in browser right away
        host: true, // listen on any IP that Docker wants to assign to it
      },
    })

Install storybook:

    npx storybook@latest init --builder=vite
    npm i -S storybook-vue-addon

Edit `.storybook/main.js`

    /** @type { import('@storybook/vue3-vite').StorybookConfig } */
    const config = {
      stories: [
        '../src/**/*.mdx', 
        '../src/**/*.stories.@(js|jsx|ts|tsx|vue)'
      ],
      addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        '@storybook/addon-interactions',
        'storybook-vue-addon',
      ],
      framework: {
        name: '@storybook/vue3-vite',
        options: {},
      },
      docs: {
        autodocs: 'tag',
      },
    }
    export default config

Create `src/stories/Button.stories.vue` and copy the following:

    <script setup>
    import Button from './Button.vue'
    </script>
    <template>
      <Stories
        title="Stories in Vue format 😍"
        :component="Button"
      >
        <Story title="Primary">
          <Button
            background="#ff0"
            label="Button"
          />
        </Story>
        <Story title="Secondary">
          <Button
            background="#ff0"
            label="😄👍😍💯"
          />
        </Story>
        <Story title="Tertiary">
          <Button
            background="#ff0"
            label="📚📕📈🤓"
          />
        </Story>
      </Stories>
    </template>
    
    <docs lang="md">
    import { Canvas } from '@storybook/blocks';
    
    # Documentation
    
    Everything in one place. Isn't it great?
    
    You can render stories in the docs using the `<Canvas>` component.
    
    <Canvas />
    </docs>

Run storybook

    npm run storybook

Error received

    Error:   Failed to scan for dependencies from entries:
      /Users/adam/Desktop/storybook/src/stories/Button.stories.js
    /Users/adam/Desktop/storybook/src/stories/Button.stories.vue
    /Users/adam/Desktop/storybook/src/stories/Header.stories.js
    /Users/adam/Desktop/storybook/src/stories/Page.stories.js
    
      ✘ [ERROR] Do not know how to load path: 
    html:/Users/adam/Desktop/storybook/src/stories/Button.stories.vue?vue&type=stories
    
        <stdin>:2:7:
          2 │ import "/Users/adam/Desktop/storybook/src/stories/Button.stories.vue"
            ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    
        at failureErrorWithLog 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1636:15)
        at /Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1048:25
        at runOnEndCallbacks 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1471:45)
        at buildResponseToResult 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1046:7)
        at /Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1058:9
        at new Promise (<anonymous>)
        at requestCallbacks.on-end 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:1057:54)
        at handleRequest (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:723:19)
        at handleIncomingPacket 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:745:7)
        at Socket.readFromStdout 
    (/Users/adam/Desktop/storybook/node_modules/esbuild/lib/main.js:673:7)
    18:27:59 [vite] ✨ new dependencies optimized: react/jsx-dev-runtime, @storybook/blocks
    18:28:00 [vite] ✨ optimized dependencies changed. reloading

**Comment by tobiasdiez** [comment]
Sorry for the late reply...holiday season 🌴 

This looks like an issue with the `entries` definition of your vite config, for some reason the stories files are seen as entry points. Strange thing is that your setup looks very similar to the vite example https://github.com/tobiasdiez/storybook-vue-addon/tree/main/examples/vite that doesn't show this issue. Could you please share a full reproduction environment (github repo or stackblitz or similar)?

**Comment by ms2d** [comment]
Hi @tobiasdiez Here is a [minimal reproducible example](https://github.com/ms2d/vue-addon-test), created using the procedure outlined above. Thanks!

**Comment by tobiasdiez** [comment]
After a bit of trial and error, I discovered there is a small mistake in your vite config. `base` is not a valid (exposed) config on `server` but has to be in the root:
```ts
export default defineConfig({
  plugins: [vue()],
  base: '',
  server: {
    open: true,
    host: true
  }
})
```
Then everything is working fine.

**Comment by ms2d** [comment]
Ahg... Fantastic -- that did it! Thanks @tobiasdiez!!!
